config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :experiences

   root "experiences#index"

end

app/models/experience.rb
class Experience < ActiveRecord::Base

  validates :rating, :presence => true
  validates :venue_name, :presence => true



  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, :presence => true, :uniqueness => true

  validates :email, :presence => true, :uniqueness => true

  has_many :experiences

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) << :username

  devise_parameter_sanitizer.for(:account_update) << :username

  end


end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: [:show, :edit, :update, :destroy]

  # GET /experiences
  # GET /experiences.json
  def index
    @experiences = current_user.experiences

  end

  # GET /experiences/1
  # GET /experiences/1.json
  def show
  end

  # GET /experiences/new
  def new
    @experience = Experience.new
  end

  # GET /experiences/1/edit
  def edit
  end

  # POST /experiences
  # POST /experiences.json
  def create
    @experience = Experience.new(experience_params)
    @experience.user_id = current_user.id

    respond_to do |format|
      if @experience.save
        format.html { redirect_to @experience, notice: 'Experience was successfully created.' }
        format.json { render :show, status: :created, location: @experience }
      else
        format.html { render :new }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiences/1
  # PATCH/PUT /experiences/1.json
  def update
    respond_to do |format|
      if @experience.update(experience_params)
        format.html { redirect_to @experience, notice: 'Experience was successfully updated.' }
        format.json { render :show, status: :ok, location: @experience }
      else
        format.html { render :edit }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiences/1
  # DELETE /experiences/1.json
  def destroy
    @experience.destroy
    respond_to do |format|
      format.html { redirect_to experiences_url, notice: 'Experience was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experience
      @experience = Experience.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experience_params
      params.require(:experience).permit(:venue_name, :favorite, :rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/_form.html.erb
<%= form_for(@experience) do |f| %>
  <% if @experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul>
      <% @experience.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :venue_name %><br>
    <%= f.text_field :venue_name %>
  </div>
  <div class="field">
    <%= f.label :favorite %><br>
    <%= f.text_field :favorite %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/experiences/edit.html.erb
<h1>Editing Experience</h1>

<%= render 'form' %>

<%= link_to 'Show', @experience %> |
<%= link_to 'Back', experiences_path %>

app/views/experiences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Experiences</h1>
<p class="btn btn-md btn-warning"><%= link_to 'New Experience', new_experience_path %></p>

<hr>
<% @experiences.each do |experience| %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= experience.venue_name %></h3>
  </div>
  <div class="panel-body">
    <dl>
      <dt>Rating</dt>
      <dd><%= experience.rating %></dd>
      <br>
       <dt>Favorite</dt>
      <dd><%= experience.favorite %> </dd>
      <br>
       <dt>Comment</dt>
      <dd><%= experience.comment %> </dd>
      </dl>
  </div>
</div>

<% end %>


<br>

app/views/experiences/new.html.erb
<h1>New Experience</h1>

<%= render 'form' %>

<%= link_to 'Back', experiences_path %>

app/views/experiences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Venue name:</strong>
  <%= @experience.venue_name %>
</p>

<p>
  <strong>Favorite:</strong>
  <%= @experience.favorite %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @experience.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @experience.comment %>
</p>

<%= link_to 'Edit', edit_experience_path(@experience) %> |
<%= link_to 'Back', experiences_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tester1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.4/flatly/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

  <style>
     body {
      padding-top: 60px;
    }

  </style>

</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand" style="text-decoration:none;">Histaurant</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <% @experiences = Experience.all %>
          <% if current_user != nil %>
          <li><a href="/experiences" style="text-decoration:none;">Experiences</a></li>
          <% else %>
          <li><a href="/experiences" style="text-decoration:none;">Experiences</a></li>

          <% end %>


        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if current_user != nil %>
          <li><a href="/users/sign_out" style="text-decoration:none;" data-method="delete">Sign Out</a></li>
          <li><a href="/users/edit" style="text-decoration:none;"><%= current_user.email %></a></li>
          <% else %>
          <li><a href="/users/sign_in" style="text-decoration:none;">Sign In</a></li>
          <li><a href="/users/sign_up" style="text-decoration:none;">Sign Up</a></li>
          <% end %>

        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>
  <div class="container">

<%= yield %>
</div>


</body>
</html>